import * as mc from "@minecraft/server";
const TYPE="lb:lich",STEP=5;
function ds(a,b){const x=a.x-b.x,y=a.y-b.y,z=a.z-b.z;return x*x+y*y+z*z;}
function near(e,r=48){const rr=r*r;return mc.world.getAllPlayers().filter(p=>p.dimension.id===e.dimension.id&&ds(p.location,e.location)<=rr);}
function nearest(e,r=48){let q,d=r*r;for(const p of mc.world.getAllPlayers()){if(p.dimension.id!==e.dimension.id)continue;const n=ds(p.location,e.location);if(n<d){q=p;d=n;}}return q?{player:q,distanceSq:d}:undefined;}
function anim(e,id){try{e.playAnimation("animation.lb.lich."+id,{blendOutTime:.15});}catch{}}
function sound(e,id,v=1,p=1){try{e.dimension.playSound(id,e.location,{volume:v,pitch:p});}catch{}}
function part(d,id,p){try{d.spawnParticle(id,p);}catch{}}
function ring(d,c,r,id="lb:obsidilith_indicator",n=16){for(let i=0;i<n;i++){const a=Math.PI*2*i/n;part(d,id,{x:c.x+Math.cos(a)*r,y:c.y+.12,z:c.z+Math.sin(a)*r});}}
function hurt(e,p,n){try{p.applyDamage(n,{cause:mc.EntityDamageCause.entityAttack,damagingEntity:e});}catch{try{p.applyDamage(n);}catch{}}}
function ratio(e){const h=e.getComponent("minecraft:health");return h?h.currentValue/Math.max(1,h.effectiveMax):1;}
function busy(e,b,c){e.setDynamicProperty("lb:lich_busy_ticks",b);e.setDynamicProperty("lb:lich_cooldown",c);}
function safe(d,t,a=10,b=16){for(let n=0;n<24;n++){const z=Math.random()*Math.PI*2,r=a+Math.random()*(b-a),x=Math.floor(t.x+Math.cos(z)*r),zz=Math.floor(t.z+Math.sin(z)*r);for(let y=Math.floor(t.y)+8;y>=Math.floor(t.y)-12;y--)try{const g=d.getBlock({x,y:y-1,z:zz}),p=d.getBlock({x,y,z:zz}),p1=d.getBlock({x,y:y+1,z:zz}),p2=d.getBlock({x,y:y+2,z:zz});if(g?.typeId!=="minecraft:air"&&p?.typeId==="minecraft:air"&&p1?.typeId==="minecraft:air"&&p2?.typeId==="minecraft:air")return{x:x+.5,y:y+.8,z:zz+.5};}catch{}}}
function missile(e,q,rage){if(!e.isValid)return;ring(e.dimension,q,2.2,"lb:obsidilith_indicator",10);mc.system.runTimeout(()=>{if(!e.isValid)return;part(e.dimension,"lb:obsidilith_burst",{x:q.x,y:q.y+.3,z:q.z});sound(e,"lb.lich.missile_shoot",.75,1.05);for(const p of near(e,50)){if(ds(p.location,q)>6.25)continue;hurt(e,p,rage?15:12);try{p.addEffect("slowness",rage?110:85,{amplifier:rage?2:1,showParticles:true});}catch{}}},10);}
function volley(e,t,rage){busy(e,70,rage?55:78);anim(e,"summon_missiles");sound(e,"lb.lich.missile_prepare",1,.95);for(let i=0;i<(rage?6:4);i++)mc.system.runTimeout(()=>{if(!e.isValid||!t.isValid)return;missile(e,{x:t.location.x+(Math.random()-.5)*3,y:t.location.y,z:t.location.z+(Math.random()-.5)*3},rage);},16+i*7);}
function minions(e,t,rage){busy(e,72,rage?65:90);anim(e,"summon_minions");sound(e,"lb.lich.minion_rune",1,.95);mc.system.runTimeout(()=>{if(!e.isValid||!t.isValid)return;const existing=e.dimension.getEntities({type:"minecraft:phantom",location:e.location,maxDistance:56}).filter(x=>x.hasTag("lb:lich_minion")&&x.getDynamicProperty("lb:lich_owner")===e.id).length,count=Math.max(0,Math.min(rage?2:1,4-existing));for(let i=0;i<count;i++){const a=Math.PI*2*i/Math.max(1,count)+Math.random()*.7,r=4+Math.random()*3;try{const ph=e.dimension.spawnEntity("minecraft:phantom",{x:t.location.x+Math.cos(a)*r,y:t.location.y+5+Math.random()*3,z:t.location.z+Math.sin(a)*r});ph.addTag("lb:lich_minion");ph.setDynamicProperty("lb:lich_owner",e.id);ph.nameTag="Lich Phantom";}catch{}}sound(e,"lb.lich.minion_summon",1,1);},34);}
function tele(e,t,rage){busy(e,58,rage?48:70);anim(e,"teleport");sound(e,"lb.lich.teleport_prepare",1,.88);mc.system.runTimeout(()=>{if(e.isValid)try{e.addEffect("invisibility",18,{amplifier:0,showParticles:false});}catch{}},12);mc.system.runTimeout(()=>{if(!e.isValid||!t.isValid)return;const p=safe(e.dimension,t.location,rage?7:10,rage?12:16);if(!p)return;try{e.teleport(p,{dimension:e.dimension,facingLocation:t.location});}catch{}try{e.dimension.playSound("mob.endermen.portal",p,{volume:1,pitch:.85});}catch{}anim(e,"unteleport");},28);}
function cometHit(e,q,rage){if(!e.isValid)return;part(e.dimension,"lb:obsidilith_burst",{x:q.x,y:q.y+.4,z:q.z});ring(e.dimension,q,5,"lb:obsidilith_burst",18);sound(e,"lb.lich.comet_shoot",1.15,rage?.9:1);for(const p of near(e,55)){const d=ds(p.location,q);if(d>27.04)continue;hurt(e,p,d<=6.76?(rage?32:27):(rage?22:18));const x=p.location.x-q.x,z=p.location.z-q.z,l=Math.max(.001,Math.hypot(x,z));try{p.applyImpulse({x:x/l*.7,y:.3,z:z/l*.7});}catch{}}}
function comet(e,t,rage){busy(e,92,rage?70:104);anim(e,"summon_fireball");sound(e,"lb.lich.comet_prepare",1.15,.9);const q={x:t.location.x,y:t.location.y,z:t.location.z};for(const d of [8,18,28])mc.system.runTimeout(()=>{if(e.isValid)ring(e.dimension,q,4.7,"lb:obsidilith_indicator",18);},d);mc.system.runTimeout(()=>cometHit(e,q,rage),40);if(rage)mc.system.runTimeout(()=>{if(!e.isValid||!t.isValid)return;const q2={x:t.location.x,y:t.location.y,z:t.location.z};ring(e.dimension,q2,4.2,"lb:obsidilith_indicator",16);mc.system.runTimeout(()=>cometHit(e,q2,true),18);},44);}
function tick(e){let b=Math.max(0,Number(e.getDynamicProperty("lb:lich_busy_ticks")??0)-STEP),c=Math.max(0,Number(e.getDynamicProperty("lb:lich_cooldown")??0)-STEP);e.setDynamicProperty("lb:lich_busy_ticks",b);e.setDynamicProperty("lb:lich_cooldown",c);const rage=ratio(e)<=.45;if(rage&&e.getDynamicProperty("lb:lich_rage")!==true){e.setDynamicProperty("lb:lich_rage",true);anim(e,"rage_mode");sound(e,"lb.lich.rage_prepare",1.25,.85);for(const p of near(e,56))try{p.sendMessage("§5[Lich] 영혼의 흐름이 폭주합니다 — 공격 주기가 빨라집니다!");}catch{}}if(b>0||c>0)return;const t=nearest(e,46);if(!t)return;const d=Math.sqrt(t.distanceSq),r=Math.random();if(r<.24)return minions(e,t.player,rage);if(r<.47||d<7)return tele(e,t.player,rage);if(r<.76)return volley(e,t.player,rage);comet(e,t.player,rage);}
function cleanup(owner){for(const id of ["overworld","nether","the_end"]){let d;try{d=mc.world.getDimension(id);}catch{continue;}for(const e of d.getEntities({type:"minecraft:phantom"}))if(e.hasTag("lb:lich_minion")&&e.getDynamicProperty("lb:lich_owner")===owner)try{e.remove();}catch{}}}
mc.world.afterEvents.entityDie.subscribe(ev=>{const e=ev.deadEntity;if(e?.typeId!==TYPE)return;cleanup(e.id);const p={x:e.location.x,y:e.location.y+1,z:e.location.z};try{e.dimension.spawnItem(new mc.ItemStack("lb:legendary_fragment",3+Math.floor(Math.random()*3)),p);}catch{}try{e.dimension.spawnItem(new mc.ItemStack("lb:epic_fragment",8+Math.floor(Math.random()*5)),p);}catch{}if(Math.random()<.28)try{e.dimension.spawnItem(new mc.ItemStack("lb:mythic_fragment",1),p);}catch{}});
mc.system.runInterval(()=>{for(const id of ["overworld","nether","the_end"]){let d;try{d=mc.world.getDimension(id);}catch{continue;}for(const e of d.getEntities({type:TYPE}))try{tick(e);}catch{}}},STEP);
mc.system.runInterval(()=>{for(const id of ["overworld","nether","the_end"]){let d;try{d=mc.world.getDimension(id);}catch{continue;}for(const e of d.getEntities({type:"minecraft:phantom"})){if(!e.hasTag("lb:lich_minion"))continue;const owner=e.getDynamicProperty("lb:lich_owner");const live=typeof owner==="string"?d.getEntities({type:TYPE}).some(x=>x.id===owner):false;if(!live)try{e.remove();}catch{}}}},200);
